version: '3'
services:
  blogpost_app:
    image: your_image_name:your_tag
    ports:
      - "4000:4000"

  couchserver:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
        - ./dbdata:/opt/couchdb/data