version: 2.1

orbs: 
  slack: circleci/slack@3.4.2 

jobs:
  build_and_deploy:
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: false
    resource_class: medium
    steps:
      - checkout

      - run:
          name: Set deployment tag env
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]
            then
              echo "export APP_ENV=prod" >> APP_ENV
            elif [ "$CIRCLE_BRANCH" == "main" ]
            then
              echo "export APP_ENV=staging" >> APP_ENV
            fi

      - run:
          name: Deployment image name env
          command: |
            echo 'export COMMIT_SHORT=$(echo $CIRCLE_SHA1 | cut -c1-7 )' >> IMG_ENV
            echo 'export IMAGE_NAME=gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$CIRCLE_BRANCH-$COMMIT_SHORT' >> IMG_ENV
            echo -n $LP_REGISTRY_SA | base64 --decode > LP_REGISTRY_SA.json
            echo -n $LP_REGISTRY_SA | base64 --decode > LP_REGISTRY_SA.json

      - run:
          name: Build docker image
          command: |
            source IMG_ENV
            source APP_ENV
            docker build --build-arg APP_ENV=$APP_ENV -t $IMAGE_NAME .

      - run:
          name: Docker push to Google Container Registry
          command: |
            source IMG_ENV
            gcloud auth configure-docker
            docker push $IMAGE_NAME

      - run:
          name: Deploy to Cloud Run
          command: |
            source IMG_ENV
            gcloud auth activate-service-account --key-file=LP_REGISTRY_SA.json
            gcloud config set project YOUR_PROJECT_ID
            gcloud config set run/region YOUR_REGION
            gcloud config set run/platform managed

            gcloud builds submit --tag $IMAGE_NAME
            gcloud run deploy YOUR_SERVICE_NAME --image $IMAGE_NAME --platform managed

      - run: exit 0

      # - slack/status: #ci-deployment
      #     channel: "C05SG7YU8HY"
      #     failure_message: "Hi $CIRCLE_USERNAME $CIRCLE_PR_USERNAME, Proses $CIRCLE_JOB $CIRCLE_PROJECT_REPONAME Branch $CIRCLE_BRANCH Gagal, Mohon untuk dicek kembali Workflow CInya, Thanks"
      #     success_message: "Hi $CIRCLE_USERNAME $CIRCLE_PR_USERNAME, Proses $CIRCLE_JOB $CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH Berhasil"
      #     webhook: $WEBHOOK_SLACK

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: [main, master]
